find_advantages_task:
  description: >
    Conduct a thorough research about the idea: {idea}.
    Find all advantages in favor of it.
  expected_output: >
    A list with 10 advantages of the idea: {idea}
  agent: optimist

find_disadvantages_task:
  description: >
    Conduct a thorough research about the idea: {idea}.
    Find all disadvantages in favor of it.
  expected_output: >
    A list with 10 disadvantages of the idea: {idea}
  agent: pessimist

decide_task:
  description: >
    Review the advantages and disadvantages of the given idea: {idea}.
    Compare them carefully and make the decision whether the idea is good or bad, and why.
  expected_output: >
    Your decision whether the idea is good or bad, and why. Short and concise answer.
    Mention only the reason for the decision, not advantages and disadvantages themselves.
    In addition to returning, log the decision using log tool.
  agent: realist
  context:
    - find_advantages_task
    - find_disadvantages_task
